package id.co.hospitops.housekeeping.infrastructure.persistence;

import id.co.hospitops.housekeeping.domain.model.HousekeepingTask;
import id.co.hospitops.housekeeping.infrastructure.persistence.entity.HousekeepingTaskJpaEntity;
import id.co.hospitops.shared.HotelId;
import id.co.hospitops.shared.ReservationId;
import id.co.hospitops.shared.RoomId;
import id.co.hospitops.shared.StaffId;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for HousekeepingTaskMapper (MapStruct @Mapper interface).
 * <p>
 * The mapper has:
 * - abstract toJpa()   — generated by MapStruct from @Mapping expressions
 * - default toDomain() — hand-written inside the interface using reconstitute()
 * <p>
 * Covers all fields including nullable reservationId and assignedTo.
 */
@DisplayName("HousekeepingTaskMapper")
class HousekeepingTaskMapperTest {

    private final HousekeepingTaskMapper mapper = Mappers.getMapper(HousekeepingTaskMapper.class);

    private static final LocalDateTime NOW = LocalDateTime.of(2025, 9, 1, 7, 0);

    // ── toJpa ────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("toJpa()")
    class ToJpa {

        @Test
        @DisplayName("maps roomId as raw UUID")
        void mapsRoomId() {
            RoomId roomId = RoomId.generate();
            HousekeepingTask task = HousekeepingTask.createManual(HotelId.generate(), roomId, "Clean");
            assertThat(mapper.toJpa(task).getRoomId()).isEqualTo(roomId.value());
        }

        @Test
        @DisplayName("maps null reservationId as null")
        void mapsNullReservationId() {
            HousekeepingTask task = HousekeepingTask.createManual(HotelId.generate(), RoomId.generate(), "Clean");
            assertThat(mapper.toJpa(task).getReservationId()).isNull();
        }

        @Test
        @DisplayName("maps non-null reservationId as raw UUID")
        void mapsNonNullReservationId() {
            ReservationId reservationId = ReservationId.generate();
            HousekeepingTask task = HousekeepingTask.createForCheckout(HotelId.generate(),
                    RoomId.generate(), reservationId);
            assertThat(mapper.toJpa(task).getReservationId())
                    .isEqualTo(reservationId.value());
        }

        @Test
        @DisplayName("maps null assignedTo as null")
        void mapsNullAssignedTo() {
            HousekeepingTask task = HousekeepingTask.createManual(HotelId.generate(), RoomId.generate(), "Clean");
            assertThat(mapper.toJpa(task).getAssignedTo()).isNull();
        }

        @Test
        @DisplayName("maps non-null assignedTo as raw UUID")
        void mapsNonNullAssignedTo() {
            StaffId staffId = StaffId.generate();
            HousekeepingTask task = HousekeepingTask.createManual(HotelId.generate(), RoomId.generate(), "Clean");
            task.assign(staffId);
            assertThat(mapper.toJpa(task).getAssignedTo()).isEqualTo(staffId.value());
        }

        @Test
        @DisplayName("maps notes correctly")
        void mapsNotes() {
            HousekeepingTask task = HousekeepingTask.createManual(HotelId.generate(), RoomId.generate(), "Vacuum carpets");
            assertThat(mapper.toJpa(task).getNotes()).isEqualTo("Vacuum carpets");
        }

        @Test
        @DisplayName("maps completed = false for a new task")
        void mapsCompletedFalse() {
            HousekeepingTask task = HousekeepingTask.createManual(HotelId.generate(), RoomId.generate(), "Clean");
            assertThat(mapper.toJpa(task).isCompleted()).isFalse();
        }

        @Test
        @DisplayName("maps completed = true for a completed task")
        void mapsCompletedTrue() {
            HousekeepingTask task = HousekeepingTask.createManual(HotelId.generate(), RoomId.generate(), "Clean");
            task.complete();
            assertThat(mapper.toJpa(task).isCompleted()).isTrue();
        }

        @Test
        @DisplayName("maps completedAt as null for a pending task")
        void mapsNullCompletedAt() {
            HousekeepingTask task = HousekeepingTask.createManual(HotelId.generate(), RoomId.generate(), "Clean");
            assertThat(mapper.toJpa(task).getCompletedAt()).isNull();
        }
    }

    // ── toDomain ─────────────────────────────────────────────────────────

    @Nested
    @DisplayName("toDomain()")
    class ToDomain {

        @Test
        @DisplayName("maps all fields when all are present")
        void mapsAllFields() {
            UUID roomId = UUID.randomUUID();
            UUID reservationId = UUID.randomUUID();
            UUID staffId = UUID.randomUUID();
            UUID id = UUID.randomUUID();

            HousekeepingTaskJpaEntity entity = HousekeepingTaskJpaEntity.builder()
                    .id(id)
                    .roomId(roomId)
                    .reservationId(reservationId)
                    .assignedTo(staffId)
                    .notes("Deep clean")
                    .completed(false)
                    .completedAt(null)
                    .createdAt(NOW)
                    .updatedAt(NOW)
                    .hotelId(java.util.UUID.randomUUID())
                    .build();

            HousekeepingTask task = mapper.toDomain(entity);

            assertThat(task.getId()).isEqualTo(id);
            assertThat(task.getRoomId().value()).isEqualTo(roomId);
            assertThat(task.getReservationId().value()).isEqualTo(reservationId);
            assertThat(task.getAssignedTo().value()).isEqualTo(staffId);
            assertThat(task.getNotes()).isEqualTo("Deep clean");
            assertThat(task.isCompleted()).isFalse();
            assertThat(task.getCompletedAt()).isNull();
            assertThat(task.getCreatedAt()).isEqualTo(NOW);
            assertThat(task.getUpdatedAt()).isEqualTo(NOW);
        }

        @Test
        @DisplayName("maps null reservationId without NPE")
        void mapsNullReservationId() {
            HousekeepingTaskJpaEntity entity = HousekeepingTaskJpaEntity.builder()
                    .id(UUID.randomUUID())
                    .roomId(UUID.randomUUID())
                    .reservationId(null)
                    .assignedTo(null)
                    .notes("Routine")
                    .completed(false)
                    .completedAt(null)
                    .createdAt(NOW).updatedAt(NOW)
                    .hotelId(java.util.UUID.randomUUID())
                    .build();

            HousekeepingTask task = mapper.toDomain(entity);

            assertThat(task.getReservationId()).isNull();
            assertThat(task.getAssignedTo()).isNull();
        }

        @Test
        @DisplayName("maps completed = true with completedAt timestamp")
        void mapsCompletedWithTimestamp() {
            LocalDateTime completedAt = NOW.plusHours(1);
            HousekeepingTaskJpaEntity entity = HousekeepingTaskJpaEntity.builder()
                    .id(UUID.randomUUID())
                    .roomId(UUID.randomUUID())
                    .reservationId(null)
                    .assignedTo(null)
                    .notes("Done")
                    .completed(true)
                    .completedAt(completedAt)
                    .createdAt(NOW).updatedAt(completedAt)
                    .hotelId(java.util.UUID.randomUUID())
                    .build();

            HousekeepingTask task = mapper.toDomain(entity);

            assertThat(task.isCompleted()).isTrue();
            assertThat(task.getCompletedAt()).isEqualTo(completedAt);
        }
    }

    // ── Round-trip ────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Round-trip: HousekeepingTask -> toJpa() -> toDomain()")
    class RoundTrip {

        @Test
        @DisplayName("checkout task preserves roomId and reservationId")
        void checkoutTaskPreservesIds() {
            RoomId roomId = RoomId.generate();
            ReservationId reservationId = ReservationId.generate();
            HousekeepingTask original = HousekeepingTask.createForCheckout(HotelId.generate(), roomId, reservationId);

            HousekeepingTask restored = mapper.toDomain(mapper.toJpa(original));

            assertThat(restored.getId()).isEqualTo(original.getId());
            assertThat(restored.getRoomId()).isEqualTo(original.getRoomId());
            assertThat(restored.getReservationId()).isEqualTo(original.getReservationId());
        }

        @Test
        @DisplayName("manual task preserves null reservationId and notes")
        void manualTaskPreservesNullReservationId() {
            HousekeepingTask original = HousekeepingTask.createManual(HotelId.generate(),
                    RoomId.generate(), "Fix broken lock");

            HousekeepingTask restored = mapper.toDomain(mapper.toJpa(original));

            assertThat(restored.getReservationId()).isNull();
            assertThat(restored.getNotes()).isEqualTo("Fix broken lock");
        }

        @Test
        @DisplayName("assigned task preserves assignedTo staff ID")
        void assignedTaskPreservesStaffId() {
            StaffId staffId = StaffId.generate();
            HousekeepingTask original = HousekeepingTask.createManual(HotelId.generate(),
                    RoomId.generate(), "Mop floors");
            original.assign(staffId);

            HousekeepingTask restored = mapper.toDomain(mapper.toJpa(original));

            assertThat(restored.getAssignedTo().value()).isEqualTo(staffId.value());
        }
    }
}
